<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error</title>
</head>
<body>
<div class="wrapper" style="width: 100%;height: 100%;display: flex;flex-direction: column;justify-content: center;align-items: center;padding: 100px 0">
    <h1 style="font-size: 72px;color:var(--color-blue)">404</h1>
    <br>
    <h2>Page not found</h2>
    <br>
    <a href="/">Back to home</a>
</div>
</body>
</html>


