<div class="card " style="width: 400px">
    <div class="card-header bg-secondary text-light">
        <strong>Login</strong>
    </div>
    <div class="card-body">
        <form action="" method="post" id="admin-login-form">
            <div class="mb-3">
                <label for="login" title="form-label"><b>User</b></label>
                <input type="text" class="form-control" id="login" name="login">
            </div>
            <div class="mb-3">
                <label for="password" title="form-label"><b>Password</b></label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <p>
                <button type="submit">
                    Login
                </button>
            </p>
        </form>
    </div>
</div>