<div style="width: 400px;border:1px solid silver;padding:20px;">
    <h1>Login</h1>
    <form action="" method="post">
        <div>
            <label for="login">Login</label>
            <input type="text" id="login" name="login">
        </div>
        <br>
        <div>
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
        </div>
        <br>
        <button type="submit">Login</button>
    </form>
</div>
