<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <?=implode('',$this->headersLinks);?>
</head>
<body style="min-height: 100vh;display: flex;justify-content: center;align-items: center;">
<?=$this->content;?>
<?=implode('',$this->bodysLinks);?>
</body>
</html>